### ISSUE TITLE
Try out VK9/a fork of DXVK on Linux and see how it does with The Sims 2

### ISSUE THREAD

**Issue by nelsonjchen** [lah7/sims-2-wine-patches#3]
https://github.com/disks86/VK9

I guess it's sort of like DXVK but for DX9. 

https://github.com/doitsujin/dxvk/pull/541

The DXVK people will not merge this fork. But it could be promising.

It might be interesting to see if converting things to Vulcan instead of OpenGL might alleviate some of those bugs. I don't know what it'll do about that notorious crazy use of shader compilation in this game. 

Some of this work might even be backportable to Windows like for the [constant Hitman 2 crashes that the game developer/graphics card vendor don't seem to be providing meaningful progress in resolving even though its a game that supposedly has current support](https://www.hitmanforum.com/t/hitman-2-constant-crashing-with-0x80000003/27218/362). Since The Sims 2 will probably stay in that state of being unsupported in the foreseeable future, I'm interested in what VK9 can offer. As of right now I've been having very similar issues to Wine OpenGL Sims 2 with my 2080 on Windows 10 1809. 

Anyway, Linux first.

**Comment by lah7** [comment]
Sounds interesting, thanks for sharing. It looks like that particular [d3d9-to-11 project has since been abandoned](https://github.com/GabrielMajeri/d3d9-to-11). :confused: 

I gave [**VK9**](https://github.com/disks86/VK9) (D3D9 to Vulkan) a quick spin, using Wine 4.3 (from winehq) and a compiled 4.0 built with Vulkan support. Seems nice and easy copying a DLL and pointing to it in **winecfg**. Although, after installing the Vulkan library packages (on Ubuntu: `libvulkan1 libvulkan1:i386 vulkan-utils`) and getting the base game to launch, I got this error:

![No compatible adapters found](https://user-images.githubusercontent.com/13032135/53761960-b43b3c00-3ebe-11e9-8043-db9219d13b2e.png)

Maybe it's because I'm using a 32-bit wine prefix... :thinking: I'll have to have another play later.

**Comment by nelsonjchen** [comment]
This seems to be a hot issue:

https://github.com/disks86/VK9/issues/100

Here's another translator:

https://github.com/Joshua-Ashton/d9vk

**Comment by nelsonjchen** [comment]
The guy also made a [DX9 to DX11 translator](https://github.com/Joshua-Ashton/dxup) too.

**Comment by nelsonjchen** [comment]
https://github.com/Joshua-Ashton/dxup was a dud. Oh well. It was worth a try.

**Comment by lah7** [comment]
I had another play with [dxup](https://github.com/Joshua-Ashton/dxup) (D3D9 → D3D11) and [DXVK](https://github.com/doitsujin/dxvk) (D3D11 → Vulkan), but no go:

![image](https://user-images.githubusercontent.com/13032135/53841733-6cd3af00-3f95-11e9-94c5-a4338f6b46c7.png)

```
002b:fixme:shell:IShellBrowser_fnOnViewWindowActive stub, 0x151f98 (0x6173a8)
002b:fixme:exec:SHELL_execute flags ignored: 0x0000000c
0047:fixme:dbghelp_dwarf:dwarf2_parse_const_type Unsupported children
0047:fixme:imm:ImmDisableTextFrameService Stub
0047:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0047:fixme:wbemprox:enum_class_object_Next timeout not supported
0047:fixme:win:EnumDisplayDevicesW ((null),0,0x351dbb4,0x00000000), stub!
0047:fixme:ddraw:ddraw7_Initialize Ignoring guid {7b891a79-e200-33c9-208d-897b48a25608}.
0047:fixme:vulkan:wine_vk_device_convert_create_info Application requested a linked structure of type 0x3b9db032.
0047:fixme:vulkan:wine_vk_device_convert_create_info Application requested a linked structure of type 0x3b9b3760.
```

I did compile Wine 4.0 with `D3D9_MAX_VERTEX_SHADER_CONSTANTF` raised from 256 to 1024... just in case...

Even with just **dxup** (D3D9 to D3D11), there's some stubs:

```
0059:fixme:dbghelp_dwarf:dwarf2_parse_const_type Unsupported children
0059:fixme:dbghelp_dwarf:dwarf2_parse_const_type Unsupported children
0059:fixme:imm:ImmDisableTextFrameService Stub
0059:fixme:win:EnumDisplayDevicesW ((null),0,0x351f4a4,0x00000000), stub!
0059:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0059:fixme:wbemprox:enum_class_object_Next timeout not supported
0059:fixme:win:EnumDisplayDevicesW ((null),0,0x351dcf4,0x00000000), stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e58240, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351e16c, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e58240, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351e16c, desc 0x2865c0 partial stub!
0059:fixme:win:EnumDisplayDevicesW ((null),0,0x351dbb4,0x00000000), stub!
0059:fixme:ddraw:ddraw7_Initialize Ignoring guid {7abc1a79-f100-4ac3-208d-bc7a706ff009}.
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc 0x286570 partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc 0x286570 partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc 0x286570 partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc 0x286570 partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e8c650, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f280, desc 0x286570 partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e545e0, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f27c, desc (nil) partial stub!
0059:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x9e545e0, format DXGI_FORMAT_B8G8R8A8_UNORM, flags 0, mode_count 0x351f27c, desc 0x286570 partial stub!
0059:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x120.
0059:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x800000c2.
0059:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x00155543.
0059:fixme:d3d11:d3d11_device_CreateRasterizerState1 iface 0x9e8b8cc, desc 0x351eb44, state 0x351eb38 stub!
0059:fixme:d3d11:d3d11_device_CreateBlendState1 iface 0x9e8b8cc, desc 0x351ea28, state 0x351ea14 stub!
0059:fixme:dxgi:dxgi_swapchain_factory_create_swapchain Unhandled mode scaling 0x2.
0059:fixme:dxgi:dxgi_factory_MakeWindowAssociation iface 0xa059900, window 0xa00ce, flags 0x2 stub!
0059:fixme:d3d11:d3d11_device_CreateRasterizerState1 iface 0x9e8b8cc, desc 0x351ec44, state 0x351ec38 stub!
0059:fixme:d3d11:d3d11_device_CreateBlendState1 iface 0x9e8b8cc, desc 0x351eb28, state 0x351eb14 stub!
```

Which shows the same D3DERR_INVALIDCALL error as above, followed by:

![image](https://user-images.githubusercontent.com/13032135/53842012-35193700-3f96-11e9-8171-7a883c89ba14.png)

Looks like there's still some work needed for these other implementations to be on par with Wine's existing D3D9 to OpenGL layer.

**Comment by tannisroot** [comment]
VK9 still can't run most games and its development is frozen.
Also, dgvoodoo2 doesn't work with it either (developer doesn't want to mess around with it).
D9VK might run it in the future but that one can't even render a triangle right now.

**Comment by tannisroot** [comment]
D9VK now runs Sims 2 pretty well.

**Comment by lah7** [comment]
Thanks for the update, let's track how we can update the README in #9.
