### ISSUE TITLE
Add family thumbnail fix

### ISSUE THREAD

**Issue by tannisroot** [lah7/sims-2-wine-patches#4]
Hi! Very cool page you got here detailing information about running Sims 2 on Linux!
May I ask if you could add some information about a no-censor mod fixing the broken thumbnails issue? I actually tweaked it a bit to disable the anti-censoring functionality itself and it still workarounds the issue, so I integrated it into the Lutris installer. You can get it from this archive https://github.com/tannisroot/installer-fixes/raw/master/sims2_fixes.tar.xz

**Comment by lah7** [comment]
Thanks for sharing - I wasn't aware of the mods and can confirm they fix the family thumbnails. :+1:

I'll update the README.
