### ISSUE TITLE
Add workarounds for skin tone mismatch and black screen

### ISSUE THREAD

**Issue by tannisroot** [lah7/sims-2-wine-patches#6]
Seems like
`boolProp   skipTangentsInVertexData true`
cheat code workarounds the skin tone mismatch issue.
And
`boolProp   createNVidiaWorkaroundTexture false`
cheat code workarounds the issue that results in a black screen after minimizing the game/changing resolution.
I suggest applying them by adding these to userstartup.cheat as they won't have any effect if you have already loaded into the family.
As usual, these workarounds are already included in the Lutris installers.

**Comment by lah7** [comment]
Thanks for sharing - the skin tone mismatch works great. :+1:

I actually run mine inside a virtual desktop _(potentially also another workaround)_ so this could be why I haven't experienced window focus/defocus issues.

I'll add both to the README.
