### ISSUE TITLE
Add D9VK to readme

### ISSUE THREAD

**Issue by tannisroot** [lah7/sims-2-wine-patches#9]
Sims 2 runs *very well** with D9VK. It still has some issues (see https://github.com/Joshua-Ashton/d9vk/issues/242) but in my opinion it has far better support for WineD3D (for example, it implements ProcessVertices, which means stuff doesn't explode with it) + you don't need patched Wine to use it, you just have to download latest master build from here: https://git.froggi.es/joshua/d9vk/-/jobs and use it kind of like DXVK.
I would update the Readme myself but it's written entirely around Wined3d so I am not sure how to rewrite it properly to acknowledge both translation layers.

**Comment by lah7** [comment]
Thanks for the update, this is very good news! It seems smoother, despite taking _a little longer_ to start. Plus, the base game (with no expansions) works as well! Excellent! :+1: :smile:

We have gathered quite a lot of info for WineD3D, which is still useful for developers looking for bugs in vanilla Wine, but for players who want to be able to _just play_ will certainly benefit with new D9VK instructions.

I was making notes as I was testing and think the best of both is to split the README into `README-WineD3D.md` and `README-D9VK.md`. I'll make the change and reference this issue when done.

**Comment by lah7** [comment]
The new README structure is in place, with D9VK here: https://github.com/lah7/sims-2-wine-patches/blob/master/README-D9VK.md

If you have any improvements, feel free to create a pull request. :smiley: Thank you for your dedication on getting this game to run better (and `#242`)! :medal_sports:
